config/routes.rb
MobileCRM::Application.routes.draw do
  resources :promotions

  resources :events

  resources :announcements

  resources :news

  resources :notifications
  match '/bulbs' , :to=> 'notifications#notification_bulbs'

  resources :offers
  

  resources :players
  
  
  match 'player_home' , :to => 'players#player_home'
  
   match '/players/test', :to => 'players#test' 
   
   match '/events/x', :to => 'events#x'
  
  resources :sessions , :only => [:new , :create , :destroy]
  
  match '/signup' , :to => 'players#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

   root :to => 'sessions#new'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :description
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/_realtimeannouncement.mobile.erb
<div id="prepend_announcement"></div>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<div data-role="page" id="announcement_page">

<div data-role="header">
	<%= image_tag '/assets/TechResultsCasinoBanner.png' , width:'100%' %>
</div>


<div class="ui-bar ui-bar-b">
	<h3 class="alignleft">News</h3>
	<div class = "alignright" id='announcement_notification'><%= link_to (image_tag ('/assets/dark.png')) , notifications_url  %></div>
	<div style="clear: both;"></div>
</div>

<div data-role="content">
		<ul data-role="listview" data-theme="d" class="ui-listview">
		<%= render '/announcements/realtimeannouncement' %>
		
		<% @announcements.each do |a| %>
				<li><%=  a.description %></li>
		<% end %>
		</ul>



</div>


<div data-role="footer" data-position="fixed" >
		<div data-role="navbar" >
			<ul>
				<li><%= link_to '' , player_home_path, 'data-icon' => 'home' %></li>
				<li id="offer1"><%= link_to '', offers_path, 'data-icon' => 'offer' %></li>
				<li id="event1"><%= link_to '' , player_home_path, 'data-icon' => 'event' %></li>
				<li id="promotion1"><%= link_to '', player_home_path, 'data-icon' => 'promotion' %></li>
				<li id="news1"><%= link_to '', announcements_path, 'data-icon' => 'news' %></li>
			</ul>
		</div><!-- /navbar -->
	</div>

	
</div>

app/views/announcements/index.mobile.erb
<div data-role="content">
	<div id="news_content">

	  <%= render '/announcements/realtimeannouncement' %>
	  <table >
		  <% @announcements.each do |a| %>
					<tr class="announcements_list">
						<td><p><%= a.description %></p></td>
					</tr>
		  <% end %>
	  </table>
	</div>
</div>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/new.mobile.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @announcement.description %>
</p>


<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>