config/routes.rb
MobileCRM::Application.routes.draw do
  resources :promotions

  resources :events

  resources :announcements

  resources :news

  resources :notifications
  match '/bulbs' , :to=> 'notifications#notification_bulbs'

  resources :offers
  

  resources :players
  
  
  match 'player_home' , :to => 'players#player_home'
  
   match '/players/test', :to => 'players#test' 
   
   match '/events/x', :to => 'events#x'
  
  resources :sessions , :only => [:new , :create , :destroy]
  
  match '/signup' , :to => 'players#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

   root :to => 'sessions#new'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :code, :description, :notification, :notificationid , :read
  

  
   def mark_as_read
	update_attribute(:read, 1)
   end
   
   def self.mark_as_read(playerid, notificationid, notification)
	notification = Notification.where('playerid=? and notificationid=? and notification=?',playerid, notificationid, notification)
	notification[0].read = 1
	notification[0].save
   end
   
   def set_bulb_to_zero
		update_attribute(:bulb, 0)
   end
   
   def self.insert_new_record(id, code, notification, description, read, playerid, bulb, startdate, enddate, drawingtime, num_of_entries)

		@notification = Notification.new
		@notification.notificationid = id
		@notification.code = code
		@notification.notification = notification
		@notification.description = description
		@notification.read = read
		@notification.playerid = playerid
		@notification.bulb = bulb
		@notification.startdate = startdate
		@notification.endate = enddate
		@notification.drawingtime = drawingtime
		@notification.num_of_entries = num_of_entries
		@notification.save
   end
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
	Notification.where('playerid = ?' , current_player.playerid).update_all(:bulb=>0)
    @notifications = Notification.where('playerid = ?' , current_player.playerid).order("created_at desc")
	

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
  
  
  def notification_bulbs
	@bulbs = Notification.where('playerid = ?' , current_player.playerid).sum(:bulb)
	
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notificationid %><br />
    <%= f.number_field :notificationid %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :notification %><br />
    <%= f.text_field :notification %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/_realtimenotification.mobile.erb
<div id="prepend_notification"></div>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing Notifications</h1>
<table>
  <thead>
    <tr>
	  
      <th>Player ID</th>
	  <th>Notification</th>
	  <th>Description</th>
      <th>Code</th>
      <th>Start Date</th>
	  <th>End Date</th>
	  <th>Drawing Time</th>
	  <th>No. of Entries</th>
	  <th>Read</th>
	  <th></th>
	  <th></th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
    <% @notifications.each do |n| %>
    <tr>
	  <td><%= n.playerid %></td>
	  <td><%= n.notification %></td>
      <td><%= n.description %></td>
	  <td><%= n.code %></td>
	  <td><%= n.startdate.strftime("%b %d, %Y") %></td>
	  <td><%= n.endate.strftime("%b %d, %Y") %></td>
	  <td><%= n.notification=='promotions'? n.drawingtime.strftime("%b %d, %Y %I:%M%p"):'-' %></td>
	  <td><%= n.notification=='promotions'? n.num_of_entries: '-' %></td>
	  <td><%= n.read %></td>
      <td><%= link_to 'Show', n %></td>
      <td><%= link_to 'Edit', edit_notification_path(n) %></td>
      <td><%= link_to 'Destroy', n, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

app/views/notifications/index.mobile.erb
<div data-role="page" id="notifications_page">




	<div data-role="header"  data-tap-toggle="false" data-position="fixed">
		<%= image_tag '/assets/header.jpg', width:'100%' %>
		<div class="ui-bar">
			
			<h3 class="alignleft">Notifications</h3>
			<div class = "alignright" id='notification_notification'>
				<%= link_to (image_tag '/assets/redlight.png', :width=>'35px', :height=>'31px') , notifications_path  %>
			</div>
			<div style="clear: both;"></div>
		</div>
		
	</div>





<div data-role="content" id="notifications_content">
	
	<% if signed_in? %>
		<%= render '/notifications/realtimenotification' %>
		<table>
		<% @notifications.each do |notification| %>
				<% notification.set_bulb_to_zero %>
				<% if notification.read == 0 %>
							<% if notification.notification == 'offers' %>
								 <tr class="notification_list_unread">
									<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag '/assets/spacer.png' %><br/><%= image_tag  notification.code+'o.png' , :width =>'60px' , :height=> '60px' %></td>
									<td>
										<h5>Offer:&nbsp;<%= notification.description %></h5>
										<p>Start Date: <%= notification.startdate.strftime("%b %d, %Y") %></p>
										<p>End Date: <%= notification.endate.strftime("%b %d, %Y") %></p>
									</td>
									
									<td class="mark_as_read">
										<%= image_tag '/assets/unread1.png' , :class=> "unread" %>
										<p class="read" style="display:none">/notifications/<%= notification.id   %></p>
									</td>
								</tr>
							<% elsif notification.notification == 'events' %>
								 <tr  class="notification_list_unread" >
									<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag '/assets/spacer.png' %><br/><%= image_tag '/assets/'+notification.code+'e.png' , :width =>'60px' , :height=> '60px' %></td>
									<td>
										<h5>Event:&nbsp;<%= notification.description %></h5>
										<p>Start Date: <%= notification.startdate.strftime("%b %d, %Y") %></p>
										<p>End Date: <%= notification.endate.strftime("%b %d, %Y") %></p>
									</td>
									
									<td class="mark_as_read">
										<%= image_tag '/assets/unread1.png' , :class=> "unread" %>
										<p class="read" style="display:none">/notifications/<%= notification.id   %></p>
									</td>
								</tr>
							<% elsif notification.notification == 'promotions' %>
								<tr class="notification_list_unread">
									<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag '/assets/default_promotion.png' , :width =>'60px' , :height=> '60px' %></td>
									<td>
										<h5>Promotion:&nbsp;<%= notification.description %></h5>
										<p>Start Date: <%= notification.startdate.strftime("%b %d, %Y") %></p>
										<p>End Date: <%= notification.endate.strftime("%b %d, %Y") %></p>
										<p>Entries: <%= notification.num_of_entries %>&nbsp;&nbsp;&nbsp;Drawing: <%= notification.drawingtime.strftime("%b %d, %Y %I:%M%p") %></p></td>
									<td class="mark_as_read">
										<%= image_tag '/assets/unread1.png' , :class=> "unread" %>
										<p class="read" style="display:none">/notifications/<%= notification.id   %></p>
									</td>
									
								</tr>
							<% end %>
				<% else %>
						
							<% if notification.notification == 'offers' %>
								 <tr class="notification_list">
									<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag '/assets/spacer.png' %><br/><%= image_tag  notification.code+'o.png' , :width =>'60px' , :height=> '60px' %></td>
									<td>
										<h5>Offer:&nbsp;<%= notification.description %></h5>
										<p>Start Date: <%= notification.startdate.strftime("%b %d, %Y") %></p>
										<p>End Date: <%= notification.endate.strftime("%b %d, %Y") %></p>
									</td>
									<td class="mark_as_read"></td>
								</tr>
							<% elsif notification.notification == 'events' %>
								 <tr  class="notification_list" >
									
									<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag '/assets/spacer.png' %><br/><%= image_tag '/assets/'+notification.code+'e.png' , :width =>'60px' , :height=> '60px' %></td>
									<td>
										<h5>Event:&nbsp;<%= notification.description %></h5>
										<p>Start Date: <%= notification.startdate.strftime("%b %d, %Y") %></p>
										<p>End Date: <%= notification.endate.strftime("%b %d, %Y") %></p>
									</td>
									<td class="mark_as_read"></td>
									
									
								</tr>
							<% elsif notification.notification == 'promotions' %>
								<tr class="notification_list">
									<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag '/assets/default_promotion.png' , :width =>'60px' , :height=> '60px' %></td>
									<td>
										<h5>Promotion:&nbsp;<%= notification.description %></h5>
										<p>Start Date: <%= notification.startdate.strftime("%b %d, %Y") %></p>
										<p>End Date: <%= notification.endate.strftime("%b %d, %Y") %></p>
										<p>Entries: <%= notification.num_of_entries %>&nbsp;&nbsp;Drawing: <%= notification.drawingtime.strftime("%b %d, %Y %I:%M%p") %></p></td>
									</td>
									<td class="mark_as_read"></td>
								</tr>
							<% end %>

				<% end %>


		<% end %>
		</table>
	<% end %>


</div>


	<div data-role="footer" data-position="fixed" data-tap-toggle="false" >
			<ul>
				<li class='fhome'><%= link_to image_tag('/assets/home.jpg', :class=> 'footer_img', :width=> '100%'), player_home_path %></li>
				<li class='foffer'><%= link_to image_tag('/assets/offers.jpg', :class=> 'footer_img',:width=> '100%'), offers_path %></li>
				<li class='fevent'><%= link_to image_tag('/assets/events.jpg',:class=> 'footer_img', :width=> '100%'), events_path %></li>
				<li class='fpromo'><%= link_to image_tag('/assets/promo.jpg',:class=> 'footer_img', :width=> '100%'), promotions_path %></li>
				<li class='fnews'><%= link_to image_tag('/assets/news.jpg', :class=> 'footer_img',:width=> '100%'), announcements_path %></li>
			</ul>
	</div>

	
</div>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/notification_bulbs.mobile.erb
<div>
<div id="unread_bulbs"><%= @bulbs %></div>
</div>

app/views/notifications/show.html.erb
<div data-role="page" id="show_notificationoffer_page">



<div data-role="header" >
	<%= image_tag '/assets/TechResultsCasinoBanner.png' , width:'100%' %>
</div>

<div class="ui-bar ui-bar-b">
	<h3 class="alignleft"><%=  @notification.description %></h3>
	<div class = "alignright" id='show_offer_notification'><%= link_to (image_tag ('/assets/dark.png')) , notifications_url  %></div>
	<div style="clear: both;"></div>
</div>


<div data-role="content">
			<div id="show_notification">
				<% @notification.mark_as_read %>
				<% Offer.mark_as_read(@notification.notificationid) %>
				<% if @notification.notification == 'offers' %>
					<div id='notification_img' style="line-height:200px;"><%= image_tag '/assets/'+@notification.code+'o.png' , :width =>'90%' , :height=> '50%' %></div>
				<% end %>
			</div>

</div>

	
	<div data-role="footer" data-position="fixed" >
		<div data-role="navbar" >
			<ul>
				<li><%= link_to '' , player_home_path, 'data-icon' => 'home' %></li>
				<li id="offer1"><%= link_to '', offers_path, 'data-icon' => 'offer' %></li>
				<li id="event1"><%= link_to '' , player_home_path, 'data-icon' => 'event' %></li>
				<li id="promotion1"><%= link_to '', player_home_path, 'data-icon' => 'promotion' %></li>
				<li id="news1"><%= link_to '', announcements_path, 'data-icon' => 'news' %></li>
			</ul>
		</div><!-- /navbar -->
	</div>

	
</div>

app/views/notifications/show.mobile.erb
<div data-role="page" id="show_notificationoffer_page">



<div data-role="header" >
	<%= image_tag '/assets/TechResultsCasinoBanner.png' , width:'100%' %>
</div>

<div class="ui-bar ui-bar-b">
	<h3 class="alignleft"><%= @notification.notification[0..-2].capitalize %>:&nbsp&nbsp&nbsp<%=  @notification.description %></h3>
	<div class = "alignright" id='show_offer_notification'>
		<% @notification.set_bulb_to_zero %>
		<% if Notification.where('playerid=?' ,current_player.playerid ).sum('bulb') == 0 %>
			<%= link_to (image_tag ('/assets/dark.png')) , notifications_path  %>
		<% else %>
			<%= link_to (image_tag ('/assets/light.png')) , notifications_path  %>
		<% end %>
	</div>	
	
	<div style="clear: both;"></div>
</div>


<div data-role="content">
			<div id="show_notification">
				<% @notification.mark_as_read %>

				<% if @notification.notification == 'offers' %>
					<% Offer.mark_as_read(@notification.notificationid) %>
					<div id='notification_img' style="line-height:200px;"><%= image_tag '/assets/'+@notification.code+'o.png' , :width =>'90%' , :height=> '50%' %></div>
				<% elsif @notification.notification == 'events' %>
					<% Event.mark_as_read(@notification.notificationid) %>
					<table>
						<tr  class="notification_event_list" data-time="<%=  @notification.created_at  %>">
							<td><%= image_tag '/assets/'+@notification.code+'e.png' , :width =>'70px' , :height=> '70px' %></td>
							<td>
								<h3><%= @notification.description %></h3>
								<p>Start Date: <%= @notification.startdate %></p>
								<p>End Date: <%= @notification.endate %></p>
							</td>	

							
						</tr>
					</table>
				<% elsif @notification.notification == 'promotions' %>
					<% Promotion.mark_as_read(@notification.notificationid) %>
					<table>
						<tr class="notification_promotion_list">
							<td class="image"><%= image_tag '/assets/default_promotion.png' , :width =>'70px' , :height=> '70px' %></td>
							<td>
								<h3><%= @notification.description %></h3>
								<p>Entries: <%= @notification.num_of_entries %></p>
								<p>Start Date: <%= @notification.startdate.strftime('%Y-%m-%d') %>&nbsp;&nbsp;&nbsp;End Date: <%= @notification.endate.strftime('%Y-%m-%d') %></p>
								<p>Drawing: <%= @notification.drawingtime %></p>
							</td>
						</tr>
					</table>
				<% end %>
			</div>

			
			
			
			
</div>

	
	<div data-role="footer" data-position="fixed" >
		<div data-role="navbar" >
			<ul>
				<li class="home1"><%= link_to '' , player_home_path, 'data-icon' => 'playershome' %></li>
				<li class="offer1"><%= link_to '', offers_path, 'data-icon' => 'offer' %></li>
				<li class="event1"><%= link_to '' , events_path, 'data-icon' => 'event' %></li>
				<li class="promotion1"><%= link_to '', promotions_path, 'data-icon' => 'promotion' %></li>
				<li class="news1"><%= link_to '', announcements_path, 'data-icon' => 'news' %></li>
			</ul>
		</div><!-- /navbar -->
	</div>

	
</div>