config/routes.rb
MobileCRM::Application.routes.draw do
  resources :promotions

  resources :events

  resources :announcements

  resources :news

  resources :notifications
  match '/bulbs' , :to=> 'notifications#notification_bulbs'

  resources :offers
  

  resources :players
  
  
  match 'player_home' , :to => 'players#player_home'
  
   match '/players/test', :to => 'players#test' 
   
   match '/events/x', :to => 'events#x'
  
  resources :sessions , :only => [:new , :create , :destroy]
  
  match '/signup' , :to => 'players#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

   root :to => 'sessions#new'

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :description
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/_realtimenews.mobile.erb
<div id="prepend_news"></div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div data-role="page" id="notifications_page">

<div data-role="header">
	<%= image_tag '/assets/TechResultsCasinoBanner.png' , width:'100%' %>
</div>


<div class="ui-bar ui-bar-b">
	<h3 class="alignleft">News</h3>
	<div class = "alignright" id='news_notification'><%= link_to (image_tag ('/assets/dark.png')) , notifications_path  %></div>
	<div style="clear: both;"></div>
</div>

<div data-role="content">

		<%= render '/news/realtimenews' %>
		<ul data-role="listview" data-theme="d">
		<% @news.each do |n| %>
				<li><%=  n.description %></li>
		<% end %>
		</ul>



</div>


<div data-role="footer" data-position="fixed" >
		<div data-role="navbar" >
			<ul>
				<li><%= link_to '' , player_home_path, 'data-icon' => 'home' %></li>
				<li id="offer1"><%= link_to '', offers_path, 'data-icon' => 'offer' %></li>
				<li id="event1"><%= link_to '' , player_home_path, 'data-icon' => 'event' %></li>
				<li id="promotion1"><%= link_to '', player_home_path, 'data-icon' => 'promotion' %></li>
				<li id="news1"><%= link_to '', news_path, 'data-icon' => 'news' %></li>
			</ul>
		</div><!-- /navbar -->
	</div>

	
</div>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/new.mobile.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @news.description %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>