config/routes.rb
MobileCRM::Application.routes.draw do
  resources :promotions

  resources :events

  resources :announcements

  resources :news

  resources :notifications
  match '/bulbs' , :to=> 'notifications#notification_bulbs'

  resources :offers
  

  resources :players
  
  
  match 'player_home' , :to => 'players#player_home'
  
   match '/players/test', :to => 'players#test' 
   
   match '/events/x', :to => 'events#x'
  
  resources :sessions , :only => [:new , :create , :destroy]
  
  match '/signup' , :to => 'players#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

   root :to => 'sessions#new'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  attr_accessible :code, :description, :enddate, :playerid, :startdate , :read

  

 def mark_as_read
	update_attribute(:read, 1)
 end
 
  def self.mark_as_read(x)
	y = Offer.find_by_id(x)
	y.read = 1
	y.save
 end
 
 def update_notification
	Notification.insert_new_record( id, code, 'offers' ,  description , read  , playerid ,  1 , startdate ,enddate, '1900-01-01' , -2)
 end
 
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.where('playerid = ?' , current_player.playerid).order("created_at desc")
	@bulbs = Notification.where('playerid = ?' , current_player.playerid).sum(:bulb)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])
	@notifications = Notification.where('playerid = ? and notificationid=? and notification=?' , current_player.playerid, @offer.id, 'offers')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
	
    @offer = Offer.new(params[:offer])
    respond_to do |format|
      if @offer.save
		@offer.update_notification
	
        format.html { redirect_to offers_url }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :playerid %><br />
    <%= f.text_field :playerid %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.datetime_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :read %><br />
    <%= f.text_field :read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/_realtimeoffer.mobile.erb
<div id="prepend_offer"></div>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing Offers</h1>
<table>
  <thead>
    <tr>
      <th>Player ID</th>
      <th>Offer Code</th>
      <th>Description</th>
      <th>Start Date</th>
	  <th>End Date</th>
	  <th>Read</th>
	  <th>Created At</th>
	  <th></th>
	  <th></th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |o| %>
    <tr>
	  <td><%= o.playerid %></td>
	  <td><%= o.code %></td>
      <td><%= o.description %></td>
	  <td><%= o.startdate.strftime("%b %d, %Y") %></td>
	  <td><%= o.enddate.strftime("%b %d, %Y") %></td>
	  <td><%= o.read %></td>
	  <td><%= o.created_at %></td>
      <td><%= link_to 'Show', o %></td>
      <td><%= link_to 'Edit', edit_offer_path(o) %></td>
      <td><%= link_to 'Destroy', o, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/index.mobile.erb
<div data-role="content" >
	<div id="offers_content">
		<% if signed_in? %>
		  <%= render '/offers/realtimeoffer' %>
		  <table>
		  <% @offers.each do |o| %>
			<% if o.read == 0 %>
					<tr class="offer_list_unread" data-time="<%=  o.created_at  %>">
						<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag  o.code+'o.png' , :width =>'60px' , :height=> '60px' %></td>
						<td class="description"><h5><%= o.description %></h5>
							<p>Start Date: <%= o.startdate.strftime("%b %d, %Y") %></p>
							<p>End Date: <%= o.enddate.strftime("%b %d, %Y") %></p>

						<td class="mark_as_read">
							<%= image_tag '/assets/unread1.png' , :class=> "unread" %>
							<p class="read" style="display:none">/offers/<%= o.id   %></p>
						</td>
					</tr>
			<% else %>
				<tr class="offer_list" data-time="<%=  o.created_at  %>">
					<td class="spacer"><%= image_tag '/assets/spacer.png' %></td><td class="image"><%= image_tag o.code+'o.png' , :width =>'60px' , :height=> '60px' %></td>
					<td class="description">
						<h5><%= o.description %></h5>
						<p>Start Date: <%= o.startdate.strftime("%b %d, %Y") %></p>
						<p>End Date: <%= o.enddate.strftime("%b %d, %Y") %></p>
					</td>

					
				</tr>
			
			<% end %>
		  <% end %>
		  </table>
		  <div id="unread_bulbs"><%= @bulbs %></div>
		<% else %>
			You are not signed in<br/>
			<% link_to signin_path %>
		<% end %>
	</div>
</div>

	

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/new.mobile.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<div data-role="page" id="show_offer_page">



<div data-role="header" >
	<%= image_tag '/assets/TechResultsCasinoBanner.png' , width:'100%' %>
</div>

<div class="ui-bar ui-bar-b">
	<h3 class="alignleft"><%=  @offer.description %></h3>
	<div class = "alignright" id='show_offer_notification'><%= link_to (image_tag ('/assets/dark.png')) , notifications_url  %></div>
	<div style="clear: both;"></div>
</div>


<div data-role="content">
			<div id="show_offer">
				<% @offer.mark_as_read %>
				<% Notification.mark_as_read(@offer.id) %>
				<div id='offer_img' style="line-height:200px;"><%= image_tag '/assets/'+ @offer.code + 'o.png' , :width =>'90%' , :height=> '50%' %></div>
			</div>

</div>

	
	<div data-role="footer" data-position="fixed" >
		<div data-role="navbar" >
			<ul>
				<li><%= link_to '' , player_home_path, 'data-icon' => 'home' %></li>
				<li id="offer1"><%= link_to '', offers_path, 'data-icon' => 'offer' %></li>
				<li id="event1"><%= link_to '' , player_home_path, 'data-icon' => 'event' %></li>
				<li id="promotion1"><%= link_to '', player_home_path, 'data-icon' => 'promotion' %></li>
				<li id="news1"><%= link_to '', announcements_path, 'data-icon' => 'news' %></li>
			</ul>
		</div><!-- /navbar -->
	</div>

	
</div>

app/views/offers/show.mobile.erb
<%= @offer.mark_as_read %>
<% @notifications.each do |n| %>
	<% n.set_bulb_to_zero %>
<% end %>

<% Notification.mark_as_read(current_player.playerid, @offer.id, 'offers') %>